pmndrs/valtio

readme.md

Hiya :wave: Love the work that's gone into this! Especially since I suppose this had a lot of edge-cases to cover against suspense and concurrent mode 👏 
I'll keep this short. Basically I love the design of the readme image and how it show cases how simple and easy to use the API is. I just feel it'd be nice to include the alt. text for screen readers.
This can be made very unobstrusive if we just include a `<details>` spoiler. I tried labelling it by placing `aria-labelledby` on the image, however it seems that GitHub doesn't like this.
Anyway, awesome work!

(docs) - Add alt-text in details/summary for readme image

---

src/index.ts
tests/basic.test.tsx

Fixes #7 : array length not updating on index assignment.
It appears that creating an empty array using `Object.create` from the prototype of the original doesn't create a proper array, just an Object which inherits from the Array prototype. Real arrays have special behaviors.
See also https://stackoverflow.com/questions/22022058/new-array-vs-object-createarray-prototype
The added tests check for the special indexing properties of an Array: a simple case of adding a sequential item, and an edge case of adding a non-contiguous one.

fix: array length for direct assignment

---

.size-snapshot.json
package.json
rollup.config.js
src/index.ts
src/vanilla.ts

close #6 
Now, we should be able to do:
```js
import { proxy, subscribe, snapshot } from 'valtio/vanilla'
```
@chase-moskal 
Not sure how this works natively in browser. It still depends on proxy-compare and it needs to be adjusted too?

vanilla support

---

tests/subscribe.test.tsx

Hey! Thanks for the work on this library, I would like to contribute.
I have added tests for the `subscribe` function, and would also like to fix the non-working ones:
1. When you call `subscribe` on a non-object property (`count` in this case) it throws an `Cannot read property 'add' of undefined` error. I'm not quite sure how to go around fixing this, my guess is to do something like a createDeepProxy much earlier?
2. When you change the state inside a subscription, it calls the subscription again leading to a `Maximum call stack size exceeded` exception. I think this `isDeepChanged` needs to be moved to into `proxy` in vanilla?
Any pointers in the right direction? Thanks a lot!

Added tests for subscribe

---

.size-snapshot.json
src/vanilla.ts
tests/class.test.tsx

continuing from #24 
As of now, proxy-compare does only support plain objects and arrays, we can't use prototypes.
This is to work around by copying keys.
I'm not confident that test cases cover everything. Help wanted.

fix: snapshots have to be plain objects

---

.size-snapshot.json
src/vanilla.ts

ref: https://github.com/pmndrs/valtio/pull/29#issuecomment-734229055
----
```tsx
const state1 = proxy({
count: 0,
get doubled() {
return `doubled: ${this.count * 2} (${performance.now()})`;
}
});
class StateClass {
count = 0;
get doubled() {
return `doubled: ${this.count * 2} (${performance.now()})`;
}
}
const state2 = proxy(new StateClass());
const Counter1: React.FC = () => {
const snapshot = useProxy(state1);
return (
<div>
<h4>Object runs the getter once</h4>
{snapshot.doubled}
<button onClick={() => ++state1.count}>+1</button>
</div>
);
};
const Counter2: React.FC = () => {
const snapshot = useProxy(state2);
return (
<div>
<h4>Class run the getter each</h4>
{snapshot.doubled}
<button onClick={() => ++state2.count}>+1</button>
</div>
);
};
const App: React.FC = () => (
<div …
```

copy object getters in proxy

---

.size-snapshot.json
src/vanilla.ts
tests/getter.test.tsx

Issue reported on Twitter: https://twitter.com/dai_shi/status/1333202394809700354
> There seems to be a bug in handling object getters. If we return non-objects, it's not undefined.

fix: object getters returns snapshot undefined

---

.size-snapshot.json
readme.md
src/utils.ts

The `subscribeKey` utility enables subscription to a primitive subproperty of a given state proxy.
Subscriptions created with `subscribeKey` will only fire when the specified property changes.

Add subscribeKey Utility

---

src/index.ts
src/useMutableSource.ts

ref #45 
This allows `forceUpdate` workaround.
Example:
```js
const state = proxy({ text: "hello" });
const TextBox = () => {
const [, forceUpdate] = useReducer((c) => c + 1, 0);
const snapshot = useProxy(state);
const onChange = (e) => {
state.text = e.target.value;
forceUpdate();
};
return <input value={snapshot.text} onChange={onChange} />;
};
```
https://codesandbox.io/s/suspicious-darwin-dv99h

fix: render from parents or something with uMS emulation hack

---

.size-snapshot.json
src/index.ts
tests/basic.test.tsx

While I was working on #54, I noticed a slight unexpected behavior. A hook can call render function several times when another hook bails out.
Turns out we should use scope subscription instead. This PR fixes it and adds the test spec for the expected behavior.

fix: better render invocation with scoped subscription

---

.size-snapshot.json
src/index.ts

- do not reuse weak map for deepChangedCache (safer)
- useLayoutEffect instead of useRef lazy init (`p` can be changed, but it would re-render anyway)
I didn't see any actual issues, but they are theoretical issues.

fix: do not reuse weak map and avoid lazy initialization

---

.size-snapshot.json
src/vanilla.ts
tests/async.test.tsx

Valtio currently does not work well with falsy values. This PR is a small improvement to allow falsy values to not be ignored.
Use case:
```js
const state = proxy({ user: user().catch(e => null) })
```

Properly check for value for promise result

---

readme.md
src/index.ts
src/vanilla.ts

close #61 
`ref` will mark an object so that it won't be wrapped by proxies when used as a (nested) property. 
```js
import { proxy, ref } from 'valtio'
const state = proxy({
obj: {},
body: ref(document.body), // this is not tracked
})
```
This `ref` is for tracking mutations only.
For render optimization (= `useProxy(state)` use case), objects could wrapped by proxies if they are plain objects, but that would only happen on demand, so it shouldn't be a problem. It doesn't influence the state object either.
```js
const state = proxy(ref(obj)) // this is not supported, it's nonsense
```

feat: ref api

---

readme.md
src/utils.ts
src/vanilla.ts
tests/computed.test.tsx

object getters are somewhat supported but not very handy.
This adds a util function to make it useful with dependency tracking.
This is for expert users: https://github.com/pmndrs/valtio/pull/71#issuecomment-770474003

feat: proxyWithComputed util

---

readme.md

And it would be cool if eslint-plugin-valtio can warn about this too!

Add dependency order information for computeds of computeds

---

tests/basic.test.tsx
tests/subscribe.test.tsx

Adds some simple tests for `ref` that was introduced in #62 and #65  fixes #66

chore(tests): add simple tests for ref rerender and subscription

---

src/index.ts
src/utils.ts
src/vanilla.ts

- rename `p` to `proxyObject` in code
- createSnapshot for readability
- always freeze snapshot (previously only in DEV)

fix: refactor and always freeze snapshot

---

tests/basic.test.tsx
tests/ref.test.tsx

Moving the tests for ref into a new file to keep code organized.

chore(test): move ref tests to new file

---

.size-snapshot.json
readme.md
src/index.ts
src/macro.ts
src/utils.ts
tests/__snapshots__/macro.test.ts.snap
tests/async.test.tsx
tests/basic.test.tsx
tests/class.test.tsx
tests/computed.test.tsx
tests/getter.test.tsx
tests/macro.test.ts
tests/mapset.test.tsx
tests/ref.test.tsx

following up: https://github.com/pmndrs/valtio/pull/100#issuecomment-792231836
- old `useProxy` -> new `useSnapshot`
- old `useBoundProxy` -> new `useProxy` (only in `valtio/macro`)
This deprecates useProxy and useLocalProxy.
Well, it's not really "breaking", as old useProxy is still exported as deprecated.

[BREAKING] rename to useSnapshot

---

readme.md
src/utils.ts
src/vanilla.ts
tests/computed.test.tsx

#90 trial made me think that valtio's computed model is different from other libraries concepts.
`proxyWithComputed` works with object getters because it is the same proxy object.
We can't support addComputed and nested with the same way.
So, here we add a new `addComputed`. Unfortunately, we can't infer typing nicely.
This should close #85 and close #86.
----
We put `addComputed` at first and then `proxyWithComputed` in readme. addComputed supports async well and we drop (undocumented / experimental) async from proxyWithComputed. However, async in addComputed is still experimental and not documented.

feat: addComputed

---

src/utils.ts

Vanilla `subscribe` takes an optional argument, `notifyInSync`, which if `true` will disable batching of subscriptions.
This PR adds the same argument to `subscribeKey`, which just passes it along to `subscribe`.
(Note, I think there are no tests for this function for any of the vanilla functions)
As requested in https://github.com/pmndrs/valtio/issues/105#issuecomment-793200092

Add notifyInSync argument to subscribeKey

---

src/utils.ts
tests/basic.test.tsx
tests/computed.test.tsx

This PR fixes a weird behavior reported in #124.
Because addComputed runs in sync, it can run get function with incomplete snapshot.
We give up running it sync, and delay one tick. This is not ideal, but until we found a better solution, this should be a safer solution.
Please note again that `addComputed` and `proxyWithComputed` are often not recommended with useSnapshot in react. Consider deriving state in render function as a primary mean.

fix: addComputed with array.pop() use case

---

babel.config.js
package.json
rollup.config.js
src/react.ts
src/utils.ts
src/vanilla.ts
yarn.lock

fix #145 
- tag `ref` type with const enum
- rename `NonPromise` to `DeepResolveType` (BREAKING CHANGE in types)
- use typescript instead of babel for cjs build
- use ts-jest for test

fix: snapshot typing for ref

---

.size-snapshot.json
src/utils.ts
tests/watch.test.tsx

Add watch to valtio/utils

---

.size-snapshot.json
src/react.ts
src/vanilla.ts

Inspired by https://github.com/reduxjs/react-redux/pull/1726#issuecomment-853424478,
this make some micro optimization. Most of them are not known if effective.
Optional chaining is more for readability/consistency.
js-framework-benchmark doesn't show much differences (left=before, right=after). valtio's use case of `forceUpdate` is very limited and probably doesn't apply for this.

chore: refactor vanilla.ts and react.ts

---

readme.md
src/utils.ts
tests/history.test.tsx

close #89 
There would be various ways to implement history features.
This one is a simple one with snapshots.
It's mostly syntax sugar and one can do something similar on user end.
So, it's more or less a reference implementation.
Everything is in the proxy object, so extending it would be easier.

feat: proxyWithHistory

---

src/utils.ts

```
inline typecasted the ref output to fix the type generation blocker
```
Attempts a fix for 
https://github.com/pmndrs/valtio/issues/191

fix(utils): declaration generation for utils.ts

---

.codesandbox/ci.json
.size-snapshot.json
package.json
rollup.config.js
src/index.ts

- Replicates: https://github.com/pmndrs/zustand/pull/507
- Attempts to fix:  https://github.com/pmndrs/valtio/issues/179
Browserify Working Example : https://codesandbox.io/s/react-browserify-forked-2ikqw?file=/src/index.js (Since the generated template isn't updated to work properly)
Working Snowpack Example: https://codesandbox.io/s/react-snowpack-forked-nq77c?file=/src/index.jsx for the attempted fix.

fix(build): Hybrid package change for ESM and CJS support

---

readme.md

fix(readme): explain how `this` works with snapshot

---

.size-snapshot.json
package.json
rollup.config.js

```
figured that .mjs is not needed for most bundlers and
causing issues with babel-loader for webpack so changed it back
```
For: https://github.com/pmndrs/valtio/issues/196#issuecomment-889756239
Sandboxes tested on PR: https://github.com/barelyhuman/valtio/pull/3

fix(pkg-exports): .mjs to .js

---

.size-snapshot.json
src/useMutableSource.ts

We use hopefully unique strings instead of symbols.
This allows to avoid `any` type.

refactor(core): useMutableSource emulation without symbol and any

---

src/utils/subscribeKey.ts

Fixes the type of the callback value of `subscribeKey`

fixing subscribeKey typing

---

src/utils/watch.ts

During investigating #284, I just noticed `watch` doesn't have a sync option.
Although we don't know any use cases, this PR adds it for the future use.

fix(utils): add watch options for notify-in-sync

---

src/vanilla.ts
tests/derive.test.tsx

close #284 
This avoids creating extra promises in a batch. Hopefully, it will improve the performance.

fix(core): improve batching

---

.github/workflows/test-multiple-versions.yml
.swcrc
package.json
yarn.lock

Using @swc/jest as the Jest transformer.
Went from 10.351 secs to 3.621 secs on my machine. That's about 65% faster.

chore(test): Use SWC as Jest transformer

---

src/index.ts
src/utils/derive.ts
src/vanilla.ts

As discussed in #297, this exposes proxy handler so that it can be extended.
This is an unstable feature and not guaranteed to be kept in the later versions.

feat: expose proxy handler experimentally

---

src/utils/derive.ts
src/vanilla.ts
tests/subscribe.test.tsx

Now, we can have more control on what to proxy and what not to proxy.
It's tricky to use `unstable_getHanlder`. It's for expert users for now.
This includes some refactors too.

fix(core): expose canProxy in handler

---

babel.config.js
package.json
rollup.config.js
src/react.ts
src/utils/proxyWithComputed.ts
src/vanilla.ts
yarn.lock

ref: https://github.com/pmndrs/valtio/issues/327#issuecomment-1018306353
close #292
`AsRef` const enum was introduced in #146 to fix some typing issue with snapshot. But, this causes some trouble while explicitly typing it, without any workarounds.
This changes `AsRef` to be _hopefully unique_ type. This allows types to be inferred. While we don't recommend, you can define the same `AsRef` on your end. It was our strong hope to hide the internal type as implementation detail and it's finally possible.
`DeepResolveType` was exported previously (which is not considered a public api, but someone might have used it), but it's now deprecated.
In case you need to specify snapshot types, there are two options.
```ts
type State = { foo?: string }
const state = proxy<State>({})
const snap = …
```

fix: avoid const enum and deprecate DeepResolveType

---

src/utils/derive.ts
tests/derive.test.tsx

@mweststrate hinted that a solution to make glitch free is simply to use a counter. https://twitter.com/mweststrate/status/1484928361084379136
So I tried. closes #296 
I had to make the subscription sync and then async in derive. There might be some edge cases this won't work well, like mixing sync and async, but the basic patterns should be covered. Let's see how it goes with releasing this.

fix(utils): make derive glitch free

---

src/utils.ts
src/utils/derive.ts
tests/derive.test.tsx

Related: https://github.com/pmndrs/valtio/issues/296#issuecomment-1020736885

fix(utils): re-implement derive to make glitch free (#335 was buggy)

---

src/react.ts
src/utils/proxyWithComputed.ts

fix #340.
Somehow, tsc compiles into weird types, if it comes with unexported types.
If we use the `class` hack in typescript playground, it works:
https://tsplay.dev/WG5kJN
So, I guess this is the issue of building, rather than a technical limitation.
Until we find a proper solution for building, let's at least fix this and release it.

fix(types): workaround for extracting types

---

src/utils/proxyWithHistory.ts
tests/history.test.tsx

fix(utils): multiple redos at once with proxyWithHistory

---

src/utils/proxyMap.ts
src/utils/proxySet.ts

fix(utils): do not depend on react in build

---

src/react.ts
src/useMutableSource.ts
src/utils/addComputed.ts
src/utils/derive.ts
src/utils/devtools.ts
src/utils/proxyMap.ts
src/utils/proxySet.ts
src/utils/proxyWithComputed.ts
src/utils/proxyWithHistory.ts
src/utils/subscribeKey.ts
src/utils/watch.ts
src/vanilla.ts

...to allow declaration merging.

refactor: prefer function declaration

---

readme.md

close #327 
---
With #359, we can do [Module Augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation).
https://codesandbox.io/s/react-typescript-forked-qphpi?file=/src/App.tsx:46-125
```ts
declare module "valtio" {
function useSnapshot<T extends object>(p: T): T;
}
```

fix(docs): add note in readme about loose typing of useSnapshot

---

docs/advanced/snapshot.mdx
docs/advanced/subscribe.mdx
docs/basic/proxy.mdx
docs/basic/useSnapshot.mdx
website/pages/_app.tsx
website/styles/prism-theme.css

This is an adaptation of https://github.com/PrismJS/prism-themes/blob/master/themes/prism-synthwave84.css but made bluer and a bit less wild. Still a bit neon. Probably could user further tweaking.

feat(website): prism theme for syntax highlights

---

package.json
tests/basic.test.tsx
yarn.lock

fix #375 by https://github.com/dai-shi/proxy-compare/pull/32

fix(core): avoid Maximum call stack size exceeded error with circular structure

---

docs/introduction/getting-started.mdx

Current getting started page on website contains an extra line.

[website] fix getting started style

---

package.json
src/utils/devtools.ts
yarn.lock

> This PR tries to bring the native `window.__REDUX_DEVTOOLS_EXTENSION__` types from redux devtools and then avoids some custom types which may be incorrect in some cases!
Related: https://github.com/pmndrs/zustand/pull/819, https://github.com/pmndrs/jotai/pull/1049

fix(utils): devtools better types

---

readme.md

I think the dependency of the `useEffect` was supposed to be `state.arr`, however, does it make a difference to have it listed in the dependencies if subscribing to it means watching for its changes anyway? 🤔 
Also added a space with `br` in the `details` section about using devtools, to avoid the image getting in the same block of the text.

Update subscribing example in readme

---

src/utils/devtools.ts
tests/devtools.test.tsx

This adds `enabled` option.
It shows the missing devtools ext warning only if `enabled=true`.
It deprecates bare string `name` option (use `{ name }` instead).
Following the change in https://github.com/pmndrs/zustand/pull/880.

fix(utils/devtools): enabled option and supress warning

---

rollup.config.js

fix(build): temporary workaround for ESM

---

docs/introduction/getting-started.mdx

There seems to have been a missing word in the last sentence of the intro. I shortened to something understandable.

fix(docs): last intro sentence correction

---

website/lib/mdx.ts
website/lib/remarkCodeSandboxURLUpdater.ts
website/package.json
website/styles/prism-theme.css
website/yarn.lock

Had a go at adding the custom remark plugin to add codepen params to the urls for embeds in the docs as suggested in comments of this PR https://github.com/pmndrs/valtio/pull/396. If this does the job I guess this one is all that is needed.

chore(website): remark plugin adds codesandbox params to urls

---

docs/introduction/getting-started.mdx
website/lib/mdx.ts

The rest of the website is comprised mostly of pages more like api docs. This is an attempt to add a more user-friendly intro and example without introducing gotchas and going too deep in the weeds.

chore(docs): add initial app example in getting started

---

docs/utils/proxyWithComputed.mdx
package.json
readme.md
src/utils/proxyWithComputed.ts
tests/computed.test.tsx
yarn.lock

close #435
This is breaking change in behavior. The API is the same, but a user needs to memoize function on their end. This allows to configure `proxy-memoize`'s options or use some other library, and even they can use without memoization.

breaking(utils): make proxyWithComputed to work with optional proxy-memoize

---

website/components/LandingPage/CodeExample.tsx
website/styles/landing-page.css

- in the animation the count presents to 1sec but not in the setInterval. Removing this to reduce confusion.
- center code and remove border radius on small screen when the code block is full width

fix(website): Remove misleading label

---

website/components/LandingPage/CodeExample.tsx
website/styles/landing-page.css

chore: adjust button style

---

.eslintrc.json
src/react.ts
src/utils/derive.ts
src/utils/devtools.ts
src/utils/proxyWithComputed.ts
src/utils/watch.ts
src/vanilla.ts
tests/derive.test.tsx

following https://github.com/pmndrs/jotai/pull/1234

refactor: prefer interfaces

---

.eslintrc.json
src/react.ts
src/utils/derive.ts
src/utils/devtools.ts
src/utils/proxyWithComputed.ts
src/utils/watch.ts
src/vanilla.ts
tests/derive.test.tsx

following https://github.com/pmndrs/zustand/pull/1106
It turns out, we don't have public interface 😓 .
This sort of reverts/revisits #474 and #493.

fix(types): use TS interfaces only for public api

---

package.json
yarn.lock

fix: proxy-compare being slow for repetitive case

---

src/vanilla.ts

a small refactor to make #528 easy to review.

refactor(vanilla): split createSnapshot function

---

src/utils/proxyWithHistory.ts
tests/history.test.tsx

Test to reproduce issue #516.
And, a fix.

fix(utils): fix proxyWithHistory behavibor with nested objects

---

readme.md

N/A
Markdown does not work when interleaved with HTML, inline code should use `<code>` instead of backticks.

docs: fix inline code format

---

docs/guides/component-state.mdx
website/lib/mdx.ts

Adds example from wiki using context for isolated component state to website docs.
- [ x] `yarn run prettier` for formatting code and docs

chore(docs): add component state guide

---

src/vanilla.ts
tests/subscribe.test.tsx

N/A
There is an edge case in the subscribe notification logic which can cause a subscriber to be called after it has been unsubscribed.
To reproduce the issue:
1. create a subscription "A"
2. create a subscription "B"
3. in the listener for "A", unsubscribe "B"
Expected result:
- "B" is never called (assuming listeners are processed in the order they were added)
Actual result:
- "B" is called once, and then never again
The fix is to check whether the subscription has been unsubscribed before firing the subscription's notification callback.
We ran into issues with this causing a "state update after unmount" error in our React app:
```
Can't perform a React state update on an unmounted component. This is a no-op, but 
it indicates a memory leak in your application. To fix, cancel all …
```

fix: subscribers should not be called after unsubscribe

---

src/utils/proxyWithHistory.ts

#561 change was bad for `proxyWithHistory`. The type alias is somehow inlined. This seems to fix it.

fix(type): proxyWithHistory

---

.github/workflows/test-old-typescript.yml
package.json

In https://github.com/pmndrs/zustand/pull/1348, I added a workflow to test against old ts versions. Let's follow it.

fix(build): test with old typescript versions and fix for old ts versions

---

src/utils/proxyMap.ts
src/utils/proxySet.ts
tests/proxyMap.test.tsx
tests/proxySet.test.tsx

**Please read https://github.com/pmndrs/valtio/pull/567#issuecomment-1273657366.**
~~Although `proxySet` and `proxyMap` have feature parity with native `Set` and `Map`, these proxies are not caught by `instanceof Set` and/or `instanceof Map`. This can be a problem when we want to validate whether a certain proxied value is either a `Set` or a `Map`, because prior to this patch, these proxies are not understood as being actual instances of `Set`/`Map`. Check out these examples:~~
```ts
if (proxySet([1, 2, 3]) instanceof Set) {
// this code will never run because this condition will always be `false`
}
if (proxyMap() instanceof Map) {
// this code will never run because this condition will always be `false`
}
```
~~After this patch, the conditions above will be satisfied and return …

fix(utils): Return accurate data at toJSON of proxySet/proxyMap

---

src/react.ts

fix(react): a workaround for missing named exports

---

src/vanilla.ts

With #599, a new implementation is possible.

refactor(vanilla): proxy state map instead of symbol

---

package.json

Clean up peer dependencies which are not actually peer deps and they cause non-deterministic pnpm behavior with projects consuming valtio. All the removed peer deps are already listed in devDeps which they seem to belong to.
Fixes #613.

fix(build): Clean up peer dependencies

---

package.json
rollup.config.js
src/macro.ts
src/macro/vite.ts
src/react-utils.ts
src/react-utils/useProxy.ts

Follow-up on https://github.com/pmndrs/valtio/discussions/620

feat(react/utils): Add useProxy() hook

---

src/vanilla.ts
tests/ref.test.tsx

`ref()` is usually used for non plain objects, but what if we use it for valtio proxy objects.
It might be more intuitive to cut the structure with a ref'ed proxy.

fix(vanilla): use case with refed proxies

---

readme.md

Related to #620.
Adds note to useProxy readme about its shallow proxy implementation and that you can only mutate on the root level.

fix(readme): add note about shallow proxy

---

src/vanilla.ts

Thought this would be more consistent with https://github.com/pmndrs/valtio/pull/653#issuecomment-1416911665.

refactor(vanilla): simplify handling object descriptor

---

package.json
src/vanilla.ts
yarn.lock

ref: https://github.com/pmndrs/valtio/pull/653#issuecomment-1418045702

fix(vanilla): improve snapshot creation ignoring object setters in prototype

---

src/vanilla.ts
tests/snapshot.test.ts

Fixes #670 
#654 broke one use case described in #670. (tbh, this isn't intended use case).
When copying from an initial object to a proxy base object, we should make it writable to make the proxy object mutable.

fix(vanilla): proxy can be created from snapshot

---

docs/api/basic/proxy.mdx
docs/introduction/getting-started.mdx

https://github.com/pmndrs/valtio/issues/689

docs: fix links url

---

docs/api/basic/useSnapshot.mdx

Potentially clarifies behavior discussion from #673.
Documents the `snap.books.map(book, i)` approach that @dai-shi mentioned is current best practice for passing stores to children.

docs(useSnapshot): Clarify parent/child useSnapshot usage.

---

docs/introduction/getting-started.mdx

I fix the API text to have proper capitalization

docs: fix API capitalization

---

docs/how-tos/some-gotchas.mdx

The current implementation of caching in snapshot has a limitation with the array mutation  #712 .
The unexpected behavior is hard to find or debug without proper description, especially since console.log and Redux devtools are not effective in this case.
Before resolving this, this needs to be described as documentation.
Therefore, add the description in some-gotchas with example cases.
Add description about #712

docs: Add Cache invalidation description in some-gotchas

---

src/vanilla/utils/devtools.ts

The current 'devtools()' util in Valtio restricts the Redux-devtools option to the 'name' field, and a custom 'enabled' field. But it might be useful to pass other devtools options too to Redux-devtools. My current case, which motivated this, is that I'm having a large data set in the proxy store (as a ref() of course), and any change to the proxy causes a significant lag in redux-devtools. This has been performance measured in Chrome. The solution is to customize redux-devtools' serializer to skip the large data part, as I don't need to see that part. This way I can further debug other perf-related bottlenecks in my heavy app. During this effort, it seemed like Valtio unnecessarily restricted the redux-devtools options object, so this change only lifts this restriction.
Fixes #

Allow passthrough of Redux devtools options

---

src/vanilla.ts
tests/snapshot.test.ts

Fixes #747
Add the 7 primitive types (`string`, `number`, `boolean`, `undefined`, `null`, `symbol`, `bigint`) to `SnapshotIgnore`, so any subtypes of these primitive types are ignored by `Snapshot<T>`.
This fixes a bug where branded/tagged primitive types (usually created by intersecting them with a faux object type) are incorrectly transformed when passed through `Snapshot<T>`.
This doesn't handle object-like branded/tagged types, but such types are less common in practice.

fix(vanilla): Snapshot<T> ignores branded primitive types

---

src/vanilla.ts
tests/snapshot.test.ts

Partially deals with #749 by disallowing property addition
(but does not completely fix it, since we still allow property removal)
As a performance optimization, we currently mark [properties of snapshots as configurable](https://github.com/pmndrs/valtio/blob/5d0eca7edc25aa7f17fb8082ef14244a35fc12b2/src/vanilla.ts#L128C10-L130). This allows users to inadvertently add or remove properties on a snapshot object with no warning. Although TypeScript typings do prevent this to a degree, it is not foolproof.
While we currently do not have a robust solution that disallows property removal while maintaining the current level performance, we can prevent addition of new properties on the snapshot by calling `Object.preventExtensions()` on it.

fix(vanilla): Prevent adding new property on snapshot

---

docs/api/utils/derive.mdx

chore(docs): fix typos in derive.mdx

---

src/vanilla.ts
tests/class.test.tsx

Fixes #759 (the feature request at the end)
Adds support for ES2022 class fields created with `Object.defineProperty()` semantics. When a configurable, enumerable, and writable (CEW) own property (usually a class field) is created on a proxy object that does not have the property, or has a CEW own property of the same name, treat it like a [[set]] trap.

feat(vanilla): Support class fields (defineProperty)

---

src/vanilla.ts
tests/class.test.tsx

This reverts commit c0bda5afd2780fb929656a87bcc9e16bcf189fd8.
Due to [what I presume is a bug in the Hermes engine](https://github.com/facebook/hermes/issues/1065), React Native projects cannot use Valtio 1.11.0. Let's revert #760 to support existing React Native users.
Fixes #765
May fix #764 (but we need confirmation from actual RN users)
This reverts #760 (c0bda5afd2780fb929656a87bcc9e16bcf189fd8). The following pattern (described in detail at #759) is no longer explicitly supported:
```js
class ValtioProxy {
constructor() {
return proxy(this)
}
}
class MyStore extends ValtioProxy {
field1 = 'asdf' // OK
field2 = []     // This works in v1.11.0.
// But when this PR is merged,
// the array will no longer be reactive
}
const store = new MyStore()
store.field2.push(1) // Will re-render …
```

Revert "feat(vanilla): Support class fields (defineProperty) (#760)"

---

docs/introduction/getting-started.mdx

I think it's suppose to say "reactivity", but I might be wrong

docs: fix typo in `getting-started.mdx`

---

docs/api/utils/devtools.mdx
src/vanilla/utils/devtools.ts

Fixes #776
I found the same issue in zustand(https://github.com/pmndrs/zustand/issues/1205#issuecomment-1221270524), so I added the same workaround(copied the type defs from `@redux-devtools/extension`)
I'm not sure if this way is a desired way, but I did it anyway..

fix(utils): improve devtools typing to avoid depending on @redux-devtools/extension

---

docs/guides/computed-properties.mdx
readme.md

#792
This is to move forward the discussion, removing derive from some docs.
To: @stephenh @alexander-entin and maybe others
I have been avoiding to push `this` usage in getters, but I change my mind. Sorry about the change, and feedback/correction are welcome.

docs: prefer object getters to derive util

---

src/vanilla.ts
tests/basic.test.tsx

fix(vanilla): respect property enumetrability

---

docs/guides/component-state.mdx
docs/how-tos/how-to-use-with-context.mdx

Adds bunshi as an alternative to `useRef` and `useConstant`, linked to docs on the bunshi website, and included a working sandbox example.

(docs) Added bunshi as an alternative and working example

---

.github/workflows/test-multiple-builds.yml
.github/workflows/test-multiple-versions.yml
package.json
rollup.config.js
src/react.ts
yarn.lock

[v2] breaking: require react 18 and drop use-sync-external-store

---

src/react/utils/useProxy.ts

Fixes https://github.com/pmndrs/valtio/discussions/808#discussioncomment-7476506
Touch a dummy prop so that it avoids re-renders if no other props are touched.
I'm not sure if we should add this hack, or just add a caveat note in docs.

fix(utils): useProxy to avoid re-renders when no props are touched

---

src/vanilla.ts
src/vanilla/utils/proxyMap.ts
src/vanilla/utils/proxySet.ts
tests/snapshot.test.ts

hey! this PR changes the `Snapshot<T>` type so that any collection types (Map, Set, WeakMap, & WeakSet) will be made read-only as well (i.e. omit mutating methods). this helps catch mistakes like the following:
```js
const snap = useSnapshot<{ users: Set<User> }>(store)
snap.users.delete(user.id) // now, "Property 'delete' does not exist"
```
this is *technically* a build-breaking change, just like adding `readonly` [was](#327), but any users affected by typed immutability have probably fixed it already. i decided to go with two internal types (`Collection` and `Readonly<T>`, which uses `Omit<T>`), resulting in slightly uglier type names (e.g. `Readonly<Set<T>>` vs. the native `ReadonlySet<T>`), but nicer typedefs.

refactor(types): make Snapshot<T> use read-only collections

---

package.json
rollup.config.js

for #810 
following https://github.com/pmndrs/zustand/pull/2380

[v2] drop es5

---

src/react.ts

following https://github.com/dai-shi/react-tracked/pull/202

[v2]: breaking: compatibility with memo

---

src/react.ts

For #810 
While working on https://github.com/valtiojs/use-valtio/pull/7, I thought this would be safe and better.

[v2] fix: make affected per proxy

---

docs/guides/migrating-to-v2.mdx

[v2] migration guide

---

.github/workflows/test-multiple-builds.yml
.github/workflows/test-old-typescript.yml
package.json
tests/memoryleaks.test.ts
yarn.lock

follow the pattern in https://github.com/pmndrs/jotai/pull/2487

refactor: memory leak test

---

package.json

https://publint.dev/rules#use_type
> a new --experimental-default-type flag to flip the default module system from "CJS-as-default" to "ESM-as-default".
wow, that will cause many problems...

[v2]: explicit package.json type field

---

docs/how-tos/how-to-reset-state.mdx

N/A
Fixes #
N/A
Added example on how to use structuredClone in v2 and the reasoning behind why it's different than v1.

docs - Added a note in how-tos/reset on how to use structuredClone

---

docs/how-tos/how-to-reset-state.mdx

N/A
Fixes #
N/A
Changed `cloneDeep` to `deepClone`. Oversight from previous PR.

fix(docs): changed cloneDeep to deepClone

---

src/vanilla/utils/proxyMap-rawMap1.ts
src/vanilla/utils/proxyMap-tree1.ts

fork of https://github.com/pmndrs/valtio/pull/965

[Not For Merge] Keyed collections 2

---

src/vanilla.ts

If I'm not mistaken, we should only run `ensureVersion` at the top object.

fix(vanilla): createSnapshot

---

docs/api/utils/proxyMap.mdx
docs/api/utils/proxySet.mdx

N/A
Fixes #
N/A
Added docs on reasoning and when to use for proxyMap and proxySet

added reasonining and when to use to proxyMap and proxySet

---

tests/async.test.tsx
tests/basic.test.tsx
tests/class.test.tsx
tests/devtools.test.tsx
tests/getter.test.tsx
tests/mapset.test.tsx
tests/optimization.test.tsx
tests/proxyMap.test.tsx
tests/proxySet.test.tsx
tests/ref.test.tsx

Tests using React Testing Library should use `screen` instead of queries methods returned by `render`.
- [ x] `pnpm run prettier` for formatting code and docs

test: use screen exposed by React Testing Library

---

src/vanilla.ts
tests/basic.test.tsx
tests/snapshot.test.ts

Fixes #985
I thought #970 change was okay, but it wasn't. Added a few tests to keep it.

fix(vanilla): revert #970

---

.eslintrc.json
package.json
pnpm-lock.yaml
tests/basic.test.tsx
tests/proxySet.test.tsx
tests/setup.ts
vitest.config.ts

Testing Library provides [Eslint plugin ](https://testing-library.com/docs/ecosystem-eslint-plugin-testing-library) which encourages to use best practices.

test: incorporate eslint-plugin-testing-library and fix reported issues

---

docs/introduction/getting-started.mdx
readme.md

* Since this is an official document, I determined that using `npm install` instead of the abbreviation `npm i` is more appropriate, so I made the change.
* In the official homepage, both `npm install` and `npm i` are used, so I standardizied them.

docs(*): change 'npm i' to 'npm install'

---

docs/api/advanced/snapshot.mdx
docs/api/basic/useSnapshot.mdx
docs/api/hacks/internals.mdx
docs/api/utils/derive.mdx
docs/guides/computed-properties.mdx
docs/how-tos/how-to-easily-access-the-state-from-anywhere-in-the-application.mdx
docs/how-tos/how-to-organize-actions.mdx
docs/how-tos/how-to-reset-state.mdx
docs/resources/libraries.mdx
website/styles/prism-theme.css

N/A
Fixes #
N/A
Updated some docs and styles for the website to make the two more consistent

updated docs and website styles

---

examples/counter/index.html
examples/counter/package.json
examples/counter/pnpm-lock.yaml
examples/counter/src/App.tsx
examples/editor-proxyWithHistory/package.json
examples/editor-proxyWithHistory/pnpm-lock.yaml
examples/editor-proxyWithHistory/src/main.tsx
examples/photo-booth-vanillajs/pnpm-lock.yaml
examples/todo-with-proxyMap/package.json
examples/todo-with-proxyMap/pnpm-lock.yaml
examples/todo/package.json
examples/todo/pnpm-lock.yaml

#1012 
Fixes #
#1012
Fixed the examples to work on stackblitz. Changed the syntax highlighting to use lowlight instead of prism so there wasn't a peer conflict for react (prism doesn't support above 16 it seems). 
Working examples (while branch exists)
https://stackblitz.com/github/pmndrs/valtio/tree/1012/examples/counter?file=package.json
https://stackblitz.com/github/pmndrs/valtio/tree/1012/examples/editor-proxyWithHistory?file=package.json
https://stackblitz.com/github/pmndrs/valtio/tree/1012/examples/photo-booth-vanillajs?file=package.json
https://stackblitz.com/github/pmndrs/valtio/tree/1012/examples/todo?file=package.json
https://stackblitz.com/github/pmndrs/valtio/tree/1012/examples/todo-with-proxyMap?file=package.json

Fixed examples to work on stackblitz

---

.github/workflows/compressed-size-action.yml
.github/workflows/cr.yml
.github/workflows/lint-and-type.yml
.github/workflows/publish.yml
.github/workflows/test-multiple-builds.yml
.github/workflows/test-multiple-versions.yml
.github/workflows/test-old-typescript.yml

* Same with https://github.com/pmndrs/zustand/pull/2918
* `pmpx` is alias version from `pnpm dlx`, i think using full name is right

chore(.github/workflows): improve workflow with removing duplicated configs

---

docs/api/advanced/subscribe.mdx
website/styles/prism-theme.css

Fixes #1031
Fixed styles for light and dark mode on `code` and `pre` elements.

Fixed `code` and `pre` elements to be styled correctly on both light and dark mode on valtio.dev

---

rollup.config.mjs

* Same with https://github.com/pmndrs/zustand/pull/2952

chore(rollup): clarify the callback argument 'e' to 'entry'

---

docs/api/utils/proxySet.mdx
src/vanilla/utils/proxySet.ts
tests/proxySet.test.tsx

N/A
- add missing `.difference` method
- fix incorrect implemented `.symmetricDifference` & `.isDisjointFrom`
- copy mdn examples as basic Unit Test
- re-order these methods according to the proposal page
the proposal
https://github.com/tc39/proposal-set-methods?tab=readme-ov-file#proposal

fix(proxySet): fix `.symmetricDifference`,`.isDisjointFrom`; add `.difference`

---

docs/resources/libraries.mdx

`tauri-plugin-valtio` is a Tauri plugin that provides a valtio integration. It can be used to save state to disk, share it across multiple windows, or even access it from the Rust backend.

docs: add `tauri-plugin-valtio` as a third-party library

---

vitest.config.mts

Fixes #
TS Error in vitest config. Coverage `provider` must be explicitly defined, otherwise produces TS error.
Also `Vitest` has nice [build-in Github reporter](https://vitest.dev/guide/reporters#github-actions-reporter).

chore: use github test reporter on CI and fix TS error

---

LICENSE

* Same with https://github.com/pmndrs/jotai/pull/2999

docs(LICENSE): keep only the initial copyright year

---

src/vanilla.ts
src/vanilla/utils/deepClone.ts

* Same with https://github.com/pmndrs/jotai/pull/3002

refactor(vanilla): change all exported functions to 'function declarations'

---

src/vanilla/utils/deepClone.ts
src/vanilla/utils/proxyMap.ts
src/vanilla/utils/proxySet.ts
tests/deepClone.test.tsx

1072
Fixes #
1072
Added `isProxyMap` and `isProxySet` methods and fixed deepClone to handle proxySets and proxyMaps. Also added tests for deepClone.
- [x ] `pnpm run fix` for formatting and linting code and docs

fix(utils): updated deepClone to handle proxyMap and proxySet

---

README.md

1077
Fixes #
1077
Changed build badge url to an existing yaml file
- [ x] `pnpm run fix` for formatting and linting code and docs

docs:fix changed readme build badge url

---

docs/how-tos/some-gotchas.mdx

#1088
Fixes #
#1088
Since the main 'valtio' package exports react modules by default, it will throw an error during builds complaining that `React` isn't available. I suggested a simple fix of imported directly from the vanilla directory which fixes the issue.
- [x ] `pnpm run fix` for formatting and linting code and docs

[Docs] Added a gotcha when importing in a non-react project

---

eslint.config.mjs
vitest.config.mts

Fixes #
* Same with https://github.com/pmndrs/zustand/pull/3116

chore(eslint): enforce file extension usage for internal modules, ignore external packages

---

docs/resources/libraries.mdx

N/A
Fixes #
N/A
Added link for `valtio-auto-persist`
- [x ] `pnpm run fix` for formatting and linting code and docs

[docs] Added link to `valtio-auto-persist` library in docs

---

tests/basic.test.tsx

Fixes #
`basic.test.tsx` has no error now.

test(basic): switch to fake timers, replace 'waitFor' with 'vi.waitFor', and 'findByText' with 'getByText'

---

tests/class.test.tsx

Fixes #
`class.test.tsx` has no error

test(class): switch to fake timers, replace 'waitFor' with 'vi.waitFor', and 'findByText' with 'getByText'

---

tests/getter.test.tsx

Fixes #
`getter.test.tsx` has no error

test(getter): switch to fake timers, replace 'waitFor' with 'vi.waitFor'

---

tests/mapset.test.tsx

test(mapset): replace 'findByText' with 'getByText', and remove inline 'Promise' delay

---

tests/devtools.test.tsx

test(devtools): switch to fake timers, add 'vi.waitFor', and replace 'findByText' with 'getByText'

---

tests/watch.test.tsx

test(watch): add 'expect' to should not infinite loop with sync case

---

tests/async.test.tsx

test(async): switch to fake timers, add 'vi.waitFor', and replace 'findByText' with 'getByText'

---

tests/ref.test.tsx

test(ref): switch to fake timers, add 'vi.waitFor', and replace 'findByText' with 'getByText'

---

tests/class.test.tsx

test(class): remove 'vi.waitFor', and add 'advanceTimersByTimeAsync' with 'act'

---

eslint.config.mjs
tests/proxyMap.bench.ts
tests/proxyMap.test.tsx
tests/snapshot.test.ts

I don't remember when I did "warn" instead of "error". Let's use `_` prefix for exceptions.

chore: strict unused check
