pmndrs/valtio

readme.md

It's not a huge use case, but a complete solution has non-React subscriptions to the store, so it's good to show that it's covered. :)

Updating the readme.md to add subscribeProxy

---

readme.md

Awesome package!
I know the readme image is pretty but it's not accessible and quite hard to read compared to a traditional readme, maybe it could be put to the bottom as the alternate view?
Anyway, here's an update to alt text!

Update readme with suspense

---

.size-snapshot.json
src/vanilla.ts
tests/subscribe.test.tsx

This batches several updates into one. This changes the update behavior in timing.

feat: batch updates

---

.size-snapshot.json
src/vanilla.ts
tests/subscribe.test.tsx

https://github.com/pmndrs/valtio/issues/20#issuecomment-731644189
The fix is rather simple.
@wilcoschoneveld How does it look?

skip setting property if not changed

---

.size-snapshot.json
src/vanilla.ts
tests/basic.test.tsx
tests/mapset.test.tsx

Map/Set are not supported, but they should be at least usable as non tracking objects.

unsupported map/set, improve delete property

---

src/vanilla.ts

@dai-shi, I think we should write tests for errors, What's your idea?

Improve non-proxy error

---

examples/README.md
examples/counter/README.md
examples/counter/package.json
examples/counter/public/index.html
examples/counter/src/App.js
examples/counter/src/index.js
examples/counter/src/styles.css

@dai-shi Here is the examples directory.

add examples to valtio

---

.size-snapshot.json
src/vanilla.ts

refactor proxyCache usage

---

.size-snapshot.json
readme.md
rollup.config.js
src/index.ts
src/utils.ts

via https://codesandbox.io/s/hopeful-merkle-ziu1h?file=/src/App.js:105-278
only change I made was added TS typings and allow the argument to be a function in case intializing the state object is non trivial and you don't want that running every render when only needed on first render

add useLocalProxy react hook

---

.size-snapshot.json
src/vanilla.ts

fix: remove bigint for rn

---

readme.md
src/index.ts
src/vanilla.ts

close #45 
Usage:
```tsx
const state = proxy({ text: "hello" });
const TextBox = () => {
const snapshot = useProxy(state, { sync: true });
const onChange = (e) => {
state.text = e.target.value;
};
return <input value={snapshot.text} onChange={onChange} />;
};
```
https://codesandbox.io/s/romantic-nobel-j7cp3?file=/src/App.js

add opt-in sync update

---

.size-snapshot.json
src/index.ts
src/vanilla.ts
tests/basic.test.tsx
tests/mapset.test.tsx

I think it shouldn't replace the state property when a promise is resolved.

support suspense error and better typing

---

.size-snapshot.json
readme.md
src/utils.ts

add utils/devtools for plain objects

---

.size-snapshot.json
src/index.ts
tests/basic.test.tsx

This is to fix an issue that was there from the beginning.
I noticed this case while maintaining other projects. It's pretty fundamental in render optimization.

fix: render from outside state

---

readme.md
src/utils.ts

fix(proxyWithComputed): support computed get shorthand

---

package.json
yarn.lock

fix: downlevel dts

---

tests/basic.test.tsx

adds test for the missing use case (i hope so) in #65

chore(test): add another test case for ref

---

src/vanilla.ts
tests/computed.test.tsx

support object setters

---

src/utils.ts

fix https://github.com/pmndrs/eslint-plugin-valtio/issues/5
Extracted a fix in #94.

fix(computed): add warning to avoid overwriting property

---

.size-snapshot.json
package.json
rollup.config.js
src/macro.ts
tests/__snapshots__/macro.test.ts.snap
tests/macro.test.ts
yarn.lock

note: test requires build in advance. FIXME if possible.

feat: valtio/macro

---

examples/counter/package.json
examples/counter/src/App.js
examples/todo/package.json
examples/todo/src/store.ts

Rename useProxy -> useSnapshot

fix: examples to follow the hook name change

---

.eslintrc.json
.size-snapshot.json
package.json
rollup.config.js
src/index.ts
src/react.ts
src/utils.ts
tsconfig.json

use relative bundle path for vanilla

---

package.json

ref: https://github.com/pmndrs/jotai/pull/359

Re-fix imports

---

.size-snapshot.json
src/macro.ts
tests/__snapshots__/macro.test.ts.snap
tests/macro.test.ts

happened to notice that boolean is not enough, so handle it with integer.

fix(macro): nested functions

---

.size-snapshot.json
readme.md
src/react.ts
src/utils.ts

drop deprecated functions for v1

---

src/react.ts

follow: https://github.com/pmndrs/zustand/pull/348

fix: better ssr detection

---

.size-snapshot.json
src/utils.ts

feat: allow import of json to devtools

---

.size-snapshot.json
package.json
src/react.ts
src/utils.ts
src/vanilla.ts
yarn.lock

Just renaming APIs internally.

chore: update proxy-compare

---

tests/ref.test.tsx

I tried replacing the fake `Promise`s with `wait*`, but I read that there's no need for that.

Remove warnings 

---

.size-snapshot.json
src/utils.ts
tests/history.test.tsx

fix(utils): proxyWithHistory to undo to initialValue

---

package.json
yarn.lock

fix: update proxy-compare

---

.eslintrc.json
babel.config.js
package.json
src/macro.ts
src/react.ts
src/utils/derive.ts
src/utils/devtools.ts
src/utils/proxyWithHistory.ts
tests/async.test.tsx
tests/basic.test.tsx
tests/class.test.tsx
tests/computed.test.tsx
tests/derive.test.tsx
tests/getter.test.tsx
tests/history.test.tsx
tests/macro.test.ts
tests/mapset.test.tsx
tests/ref.test.tsx
tests/watch.test.tsx
tsconfig.json

follow https://github.com/pmndrs/jotai/pull/656
and use react-jsx now.

chore: update eslintrc and use react-jsx

---

readme.md

Fix little typo in readme about watch example

Update watch example in readme.md

---

package.json
src/utils/derive.ts
src/utils/proxyWithHistory.ts
tsconfig.json
yarn.lock

following https://github.com/pmndrs/jotai/pull/678

refactor: stricter tsconfig

---

.eslintrc.json
package.json
tests/async.test.tsx
tests/basic.test.tsx
tests/class.test.tsx
tests/computed.test.tsx
tests/derive.test.tsx
tests/getter.test.tsx
tests/history.test.tsx
tests/mapset.test.tsx
tests/ref.test.tsx
tests/subscribe.test.tsx
tests/watch.test.tsx
tsconfig.json

Following https://github.com/pmndrs/jotai/pull/738

refactor(test): use aliases

---

tests/subscribe.test.tsx

chore(tests): hide expected warning message

---

.eslintrc.json
src/macro.ts
src/utils/devtools.ts
src/vanilla.ts

following https://github.com/pmndrs/zustand/pull/678

chore(eslint): add recommended rules and etc

---

rollup.config.js

Follow the thread: https://github.com/pmndrs/zustand/pull/740
Hi @dai-shi , I did the same config here.

fix(build): Generate umd and system files

---

.github/workflows/lint-and-type.yml
website/.eslintrc.json
website/components/layouts/DocLayout/DocLayout.tsx

well, I thought the eslint rule isn't important, but actually it is.

fix(website): eslint config

---

examples/editor-proxyWithHistory/README.md

This PR add the readme, so it's consistent with the other examples

chore(examples): add readme for proxyWithHistory example

---

docs/basic/proxy.mdx

First go at this. Improvement suggestions 🙏

chore(docs): proxy

---

src/utils/watch.ts
tests/watch.test.tsx

fix(utils/watch): avoid infinite loop with sync

---

package.json
yarn.lock

close #392 
Upstream PR: https://github.com/dai-shi/proxy-compare/pull/34

fix: support tracking hasOwnProperty in render optimization

---

docs/introduction/getting-started.mdx
src/utils/derive.ts
tests/derive.test.tsx

based on tests in #387
close #349 
The implementation is not super readable. I hope we can refactor it somehow.

fix(utils): avoid infinite loop with mutual derive usage

---

src/vanilla.ts

This PR refactors vanilla.ts to use default parameter instead of if statement.

refactor(vanilla): Use the default parameters

---

src/utils/devtools.ts

refactor(utils): small refactor in devtools

---

src/react.ts

fix(react): do not omit getServerState in useSyncExternalStore

---

src/vanilla.ts
tests/basic.test.tsx

fix(vanilla): support undefined property in proxy

---

docs/utils/devtools.mdx
readme.md
src/utils/devtools.ts

devtools(state, name) is deprecated

chore: devtools docs

---

src/react.ts
tests/basic.test.tsx

fix(react): nested component to update from parent (regression in #234)

---

src/react.ts

What I did in #461 isn't correct in terms of useSyncExternalStore usage.
This should fix it.

fix(react): re-implement for #461

---

readme.md

Fixed typo "Suscribe" to "Subscribe".

docs: typo in readme.md

---

docs/readme.md
readme.md

fix(readme): add compatibility section

---

docs/introduction/getting-started.mdx

missing closing bracket ('>') in span

fix error in code snippet

---

website/components/LandingPage/CodeExample.tsx
website/styles/landing-page.css

styles assigned to pre tag on landing page were conflicting with our documentation pages. This PR fixes that.

Update styles for pre tag on landing page

---

docs/basic/useSnapshot.mdx

fix(docs): follow #425 change

---

src/vanilla.ts

refactor(core): shave bytes

---

tests/basic.test.tsx
tests/derive.test.tsx
tests/devtools.test.tsx

following https://github.com/pmndrs/jotai/pull/1396

chore(tests): enable StrictMode as much as possible

---

docs/resources/learn.mdx

Share examples of 7guis with Valtio for learning and comparison
- [x ] `yarn run prettier` for formatting code and docs

chore(website): add 7GUIs resource

---

website/components/SEO/SEO.tsx
website/components/layouts/Header/Header.tsx
website/pages/index.tsx

fix(docs): website title

---

src/utils/subscribeKey.ts
tests/computed.test.tsx

fix(utils): revert subscribeKey impl to the original one (without ops)

---

src/react.ts
src/utils/proxyWithComputed.ts
src/utils/proxyWithHistory.ts
src/vanilla.ts

refactor(types): rename internal types when importing

---

website/components/LandingPage/GettingStarted.tsx
website/styles/landing-page.css

Fixes  #577
Fixes the code playground appearing full width on relatively large screens.

Update breakpoints for valtio homepage

---

src/vanilla.ts

fix(types): fix subscribe return type

---

package.json
src/react.ts
yarn.lock

ref: https://github.com/dai-shi/proxy-compare/pull/48

chore(deps): update proxy-compare

---

docs/api/utils/proxyWithComputed.mdx
package.json
readme.md
tests/computed.test.tsx
yarn.lock

chore(deps): update dev dependencies

---

readme.md

And also follow `$state` convention. #620

fix(readme): add note for useProxy usage

---

docs/api/utils/derive.mdx
docs/how-tos/how-to-avoid-rerenders-manually.mdx
docs/how-tos/how-to-easily-access-the-state-from-anywhere-in-the-application.mdx
docs/how-tos/how-to-organize-actions.mdx
docs/how-tos/how-to-persist-states.mdx
docs/how-tos/how-to-reset-state.mdx
docs/how-tos/how-to-split-and-compose-states.mdx
docs/how-tos/how-to-use-with-context.mdx
docs/how-tos/how-valtio-works.mdx
docs/how-tos/some-gotchas.mdx
docs/resources/libraries.mdx
website/lib/mdx.ts

This adds all [wiki pages](https://github.com/pmndrs/valtio/wiki) to the `docs` folder verbatim. Once this is merged in, I'll update wiki pages to add links to the respective files.

Add all wiki pages

---

docs/api/advanced/subscribe.mdx
docs/api/utils/watch.mdx

Just clarifying the non-usage tracking nature of `watch`.

docs: Clarify behavior of watch.

---

docs/api/advanced/snapshot.mdx
docs/api/advanced/subscribe.mdx
docs/api/basic/proxy.mdx
docs/api/basic/useSnapshot.mdx
docs/api/hacks/getVersion.mdx
docs/api/utils/watch.mdx
docs/guides/component-state.mdx
docs/guides/computed-properties.mdx

Just adding things that personally I have learned/think is useful to know so far.

docs: Doc updates on classes.

---

docs/resources/libraries.mdx

add two new libs, and other them alphabetically.

chore(docs): update libraries

---

package.json
src/react.ts
src/vanilla.ts
yarn.lock

and some refactors.
close #519 again.

fix(vanilla): improve performance with configurable property on snapshot

---

tests/snapshot.test.ts

#664 
Add a regression test for #664 .
Granted, this doesn't truly ensure proxy-compare doesn't make a copy, but it still seems worthwhile to prevent accidental regressions.

chore(tests): Add test that we probably avoid copies.

---

rollup.config.js

following https://github.com/pmndrs/jotai/pull/1780

fix(build): possibley improve ESM for production build

---

docs/resources/community.mdx

fix(docs): fix discord link

---

src/react/utils/useProxy.ts

Fixes #683
pass-through `useSnapshot` opts in `useProxy`
- [x ] `yarn run prettier` for formatting code and docs

fix(react/utils): added useProxy parameter for opts #683

---

docs/guides/computed-properties.mdx

fix(docs): Note on what a computed prop could reference

---

rollup.config.js
src/vanilla/utils/devtools.ts

follows https://github.com/pmndrs/jotai/pull/1978

fix(build): mode env for "import" condition"

---

docs/introduction/getting-started.mdx

Fixes #751
There was a bug in the todos example.

fix(docs): bugs in todos example

---

src/vanilla/utils/devtools.ts

following https://github.com/pmndrs/zustand/pull/2099

fix(types): mitigate devtools typing

---

package.json

Publint warnings -> https://publint.dev/valtio@1.11.3
Apply publint recommendations

Apply publint recommendations

---

.github/workflows/test-old-typescript.yml
package.json
tests/async.test.tsx
tests/computed.test.tsx
tests/derive.test.tsx
yarn.lock

breaking: require TS 4.5 at least

---

package.json
rollup.config.js

For #810 
The "module" condition isn't official, but helped for some cases. Jotai v2 has dropped it and it seems good.

[v2] breaking: drop "module" condition

---

src/react.ts
src/vanilla.ts
tests/snapshot.test.ts

[v2] export Snapshot type

---

rollup.config.js

follow https://github.com/pmndrs/jotai/pull/2419

build: target es2018

---

rollup.config.js

for #810 
there was an issue in #865.
following https://github.com/pmndrs/zustand/pull/2433

[v2] fix rollup config for cjs

---

.github/workflows/compressed-size-action.yml
.github/workflows/cr.yml
.github/workflows/lint-and-type.yml
.github/workflows/publish.yml
.github/workflows/test-multiple-builds.yml
.github/workflows/test-multiple-versions.yml
.github/workflows/test-old-typescript.yml

Upstream: https://github.com/pnpm/action-setup/issues/135#issuecomment-2206861174

ci: fix pnpm setup

---

.github/workflows/test-old-typescript.yml
tests/snapshot.test.ts
tsconfig.json

following https://github.com/pmndrs/jotai/pull/2664

chore: enable verbatimModuleSyntax in tsconfig

---

examples/editor-proxyWithHistory/package.json
examples/photo-booth-vanillajs/index.html
package.json

change emoji from 💊 to 🧙

---

src/vanilla.ts

breaking(vanilla): do not handle promises

---

.github/workflows/cr.yml

This add all of the examples as templates in pkg.pr.new!

feat: pkg.pr.new templates

---

docs/guides/migrating-to-v2.mdx

Fixes #938
Clarify about impure proxy().

docs: improve v2 migration guide

---

docs/resources/libraries.mdx

N/A
Fixes #
N/A
Added a link to Zod wrapper library (https://github.com/valtiojs/valtio-zod)

Added valtio-zod to library list in docs

---

docs/guides/migrating-to-v2.mdx

docs: add useLayoutEffect warning mitigation

---

.github/workflows/test-old-typescript.yml
package.json
pnpm-lock.yaml
src/vanilla.ts
src/vanilla/utils/deepClone.ts
src/vanilla/utils/subscribeKey.ts
tsconfig.json

following https://github.com/pmndrs/jotai/pull/2687

chore: enable isolatedDeclarations

---

tests/proxyMap.test.tsx
tests/snapshot.test.ts

just to make sure before we refactor proxyMap.

chore(test): add some cases with snapshot

---

src/vanilla.ts

I found a potential bug while working on #966.

fix(vanilla): createSnapshotDefault

---

src/vanilla.ts

chore(vanilla): mark op unstable and internal

---

src/vanilla/utils/proxyMap.ts
src/vanilla/utils/proxySet.ts

N/A
Fixes # N/A
Added jsdoc comments for proxyMap and proxySet

added jsdoc comments for proxyMap and proxySet

---

.github/workflows/compressed-size-action.yml
.github/workflows/lint-and-type.yml
.github/workflows/publish.yml
.github/workflows/test-multiple-builds.yml
.github/workflows/test-multiple-versions.yml
.github/workflows/test-old-typescript.yml

* Same with https://github.com/pmndrs/zustand/pull/2893, https://github.com/pmndrs/jotai/pull/2857

chore(.github/workflows): update actions/setup-node's node-version 18 to 20

---

.github/workflows/compressed-size-action.yml
.github/workflows/cr.yml

* same with https://github.com/pmndrs/zustand/pull/2894

chore(.github/workflows): unify format style

---

.github/workflows/test-multiple-versions.yml

* Same with https://github.com/pmndrs/zustand/pull/2920

chore(.github/workflows/test-multiple-versions.yml): improve workflow with removing duplicated configs

---

.github/workflows/compressed-size-action.yml
.github/workflows/cr.yml
.github/workflows/lint-and-type.yml
.github/workflows/publish.yml
.github/workflows/test-multiple-builds.yml
.github/workflows/test-multiple-versions.yml
.github/workflows/test-old-typescript.yml

* Same with https://github.com/pmndrs/zustand/pull/2933

chore(.github/workflows): change 'node-version' to 'lts/*' in 'actions/setup-node'

---

eslint.config.mjs
package.json
pnpm-lock.yaml

* Same with https://github.com/pmndrs/zustand/pull/3043

chore(eslint.config.mjs): update 'eslint-plugin-react-hooks', 'eslint-plugin-react-compiler' config

---

docs/resources/libraries.mdx

Fix url of a third-party library.

docs: fix `tauri-plugin-valtio` url

---

src/react.ts
src/vanilla.ts
src/vanilla/utils/deepClone.ts
src/vanilla/utils/devtools.ts
src/vanilla/utils/proxyMap.ts
src/vanilla/utils/proxySet.ts

N/A
Fixes #
N/A
Added tsdoc comments throughout
- [x ] `pnpm run fix` for formatting and linting code and docs

[docs]: TS-Doc comments added

---

docs/resources/libraries.mdx

n/a
Fixes #
n/a
added valtio-fsm to libraries and fixed link for valtio-persist
- [ x ] `pnpm run fix` for formatting and linting code and docs

[docs] added valtio-fsm to libraries and fixed link for valtio-persist

---

package.json

following https://github.com/pmndrs/jotai/pull/3042

fix(package): react-native condition

---

src/react.ts
tests/basic.test.tsx
tests/class.test.tsx
tests/ref.test.tsx

chore: fix eslint warnings

---

tests/deepClone.test.tsx

chore(tests/deepClone): remove unused imports

---

docs/resources/libraries.mdx

N/A
Fixes #N/a
Added valtio-plugin github link to list
- [ x] `pnpm run fix` for formatting and linting code and docs

docs: added valtio-plugin library to list

---

tests/proxyMap.test.tsx

test(proxyMap): switch to fake timers, replace 'waitFor' with 'vi.waitFor'

---

tests/async.test.tsx
tests/getter.test.tsx
tests/optimization.test.tsx
tests/proxyMap.test.tsx
tests/proxySet.test.tsx
tests/ref.test.tsx

test(*): remove 'vi.waitFor', and add 'advanceTimersByTimeAsync' with 'act'

---

src/vanilla.ts
tests/subscribe.test.tsx

Fixes #1152
remove listeners.size check in `ensureVersion` to make sure version changed.

fix(vanilla): snapshot should change with subscription after deleting nested props

---

tests/memoryleaks.test.ts

https://github.com/pmndrs/valtio/pull/1153#issuecomment-3193670394

test: add more memory leak cases

---

.github/workflows/compressed-size.yml
.github/workflows/preview-release.yml
.github/workflows/publish.yml
.github/workflows/test-multiple-builds.yml
.github/workflows/test-multiple-versions.yml
.github/workflows/test-old-typescript.yml
.github/workflows/test.yml

ci(.github/workflows): update 'actions/checkout' and 'actions/setup-node' to v5
